### ISSUE TITLE
Can keep on rating an item after each page refresh

### ISSUE THREAD

**Issue by Sanderha** [sheadawson/silverstripe-rateable#11]
Hi again, and thanks for fixing the last issue so fast!

It seems the userHasRated() function in the RateableService class is broken. I can rate an item, refresh the page, and rate again. 

Any ideas why this happens?

**Comment by sheadawson** [comment]
I can't seem to replicate this issue sorry. What browser/os are you on?

**Comment by Sanderha** [comment]
Im using OSX Yosemite, and the problem exists on Chrome, Firefox and Safari. I am also not logged into the system in any way (users are able to rare without being logged in whatsoever).

**Comment by Sanderha** [comment]
Update:
It seems there is no functionality for not being able to spam-rate, when there is no member logged in, or a session is set.

Maybe we should create a Session when the site is opened?

**Comment by sheadawson** [comment]
Yeap if something hasn't started the session yet, the session id doesn't get saved against the rating. Fixed. Thanks for raising that one!
