### ISSUE TITLE
when adding rateable to SiteTree i see it on all pages

### ISSUE THREAD

**Issue by wernerkrauss** [sheadawson/silverstripe-rateable#12]
even on security/login

should we check if the page has an positive ID set before rendering the $RateableUI?

**Comment by sheadawson** [comment]
I fixed this a week or so ago in e34e3e404be8a2bc57069e3322848a96cad7a31d have you got the latest?

**Comment by wernerkrauss** [comment]
oops, i was on 1.0, switched to dev-master for makeing the pr for #13 , now it works. Sorry for the inconvenience!

**Comment by sheadawson** [comment]
No problem. 1.1.1 is the latest stable and has that fix. Thanks in advance
for the translation work!

On Tue, Sep 8, 2015 at 10:05 PM, wernerkrauss <notifications@github.com>
wrote:

> oops, i was on 1.0, switched to dev-master for makeing the pr for #13
> <https://github.com/sheadawson/silverstripe-rateable/issues/13> , now it
> works. Sorry for the inconvenience!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sheadawson/silverstripe-rateable/issues/12#issuecomment-138503221>
> .
>



-- 
*Shea Dawson*
Web Developer
LiveSource

*mobile* +64 20 4028 5647
*skype* squatchnz
*email* shea@livesource.co.nz
*web *www.livesource.co.nz
